// ===========================================================================
//  setup-mail.js — write mail.env.bat by copying the SMTP settings that are
//  already working in another local project's .env.
//
//  The password is moved file-to-file and is never printed. Re-run this if the
//  source .env changes; delete mail.env.bat to undo.
//
//  Run:  node setup-mail.js
// ===========================================================================
const fs = require("fs");
const path = require("path");

// Source of truth for the Google Workspace app password (already proven working).
const SOURCE_ENV = "D:\\CitilightDashboard\\StableNewBackend\\Velocity-backend\\.env";
const TARGET = path.join(__dirname, "mail.env.bat");

// Who the report goes to. Change these two lines to re-point the report.
const MAIL_TO = "aditimishraofficial10@gmail.com";
const MAIL_CC = "";

// Pull KEY=value out of a .env, tolerating quotes, CRLF and stray spaces.
function readEnv(file) {
  const out = {};
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf("=");
    if (i < 1) continue;
    out[line.slice(0, i).trim()] = line.slice(i + 1).trim().replace(/^["']|["']$/g, "");
  }
  return out;
}

if (!fs.existsSync(SOURCE_ENV)) {
  console.error(`Source .env not found:\n  ${SOURCE_ENV}`);
  console.error("Edit SOURCE_ENV at the top of this file, or fill mail.env.bat by hand.");
  process.exit(1);
}

const env = readEnv(SOURCE_ENV);
const user = env.SMTP_USER || "";
// Google displays app passwords in 4-character groups; the spaces are cosmetic.
const pass = (env.SMTP_PASS || "").replace(/\s+/g, "");
const host = env.SMTP_HOST || "smtp.gmail.com";
const port = env.SMTP_PORT || "587";

const missing = [];
if (!user) missing.push("SMTP_USER");
if (!pass) missing.push("SMTP_PASS");
if (missing.length) {
  console.error(`${SOURCE_ENV} has no ${missing.join(" / ")} — nothing to copy.`);
  process.exit(1);
}

// `set "K=V"` is the .bat form that survives trailing spaces and most punctuation.
// Anything cmd would still mangle means the value must be quoted by hand instead.
if (/[%\r\n"]/.test(pass)) {
  console.error("The password contains a character cmd cannot carry safely (% or a quote).");
  console.error("Fill mail.env.bat by hand instead.");
  process.exit(1);
}

if (fs.existsSync(TARGET)) console.log("mail.env.bat already existed — overwriting it.");

fs.writeFileSync(TARGET, [
  "@echo off",
  "REM Generated by setup-mail.js — copied from the Velocity-backend .env.",
  "REM This file holds a live app password. It is gitignored; do not share it.",
  "",
  `set "MAIL_USER=${user}"`,
  `set "MAIL_PASS=${pass}"`,
  `set "MAIL_FROM=${user}"`,
  "",
  `set "MAIL_TO=${MAIL_TO}"`,
  `set "MAIL_CC=${MAIL_CC}"`,
  "",
  `set "MAIL_HOST=${host}"`,
  `set "MAIL_PORT=${port}"`,
  `set "MAIL_ENABLED=1"`,
  "",
].join("\r\n"));

console.log("Wrote mail.env.bat");
console.log(`  from/user : ${user}`);
console.log(`  password  : ${"*".repeat(pass.length)}  (${pass.length} chars, copied unseen)`);
console.log(`  to        : ${MAIL_TO}`);
console.log(`  server    : ${host}:${port}`);
console.log("\nNext:  cmd /c \"call mail.env.bat && node test-mail.js\"");
